baseurl: vandyliu.com/hugo-website
languageCode: en-us
theme: hugo-theme-stack
paginate: 10
title: Vandy Liu

# Change it to your Disqus shortname before using
disqusShortname: hugo-theme-stack

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn
DefaultContentLanguage: en

publishDir: docs

permalinks:
    post: /p/:slug/
    project: /proj/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    projects:
        - project
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2020
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 👨‍💻
        subtitle: A computer science student who enjoys doing stuff with computers and who needs to change this text in the future.
        avatar:
            local: false
            src: /good.JPG

    article:
        math: false
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: false
        provider: disqus
        utterances:
            repo:
            issueTerm: pathname
            label:
            theme: preferred-color-scheme

    widgets:
        enabled:
            - search
            - tag-cloud

        tagCloud:
            limit: 10

    opengraph:
        linkedin:
            # Your Twitter username
            site: https://www.linkedin.com/in/vandy-liu/

            # Available values: summary, summary_large_image
            card: summary_large_image
        github:
            site: https://github.com/vandyliu
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true
        
        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          pre: home

        - identifier: about
          name: About
          url: about
          weight: -90
          pre: user

        - identifier: projects
          name: Projects
          url: projects
          weight: -80
          pre: projects

        - identifier: resume
          name: Resume
          url: resume
          weight: -70
          pre: resume

        - identifier: search
          name: Search
          url: search
          weight: -60
          pre: search

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    highlight:
        noClasses: false
